// auto-generated by lnp-tbox.sage.
// 
// protocol is statistically complete with correctness error >= 1 - 2^(-3)
// protocol is simulatable under MLWE(67,26,[-1,1])
// protocol is knowledge-sound with knowledge error <= 2^(-127.0) under MSIS(15,189,2^(50.481116))
// 
// Ring
// degree d = 64
// modulus q = 162259276829213363391578010288637, log(q) ~ 107.0
// factors q = q1
// 
// Compression
// D = 27
// gamma = 57938773644, log(gamma) ~ 35.75381
// 
// Dimensions of secrets
// s1: m1 = 96
// m: l = 0
// s2: m2 = 93
// 
// Size of secrets
// l2(s1) <= alpha = 4269351.0
// m unbounded
// s2 uniform in [-nu,nu] = [-1,1]
// 
// Norm proofs
// binary: yes (dimension: 32)
// exact euclidean: yes (dimensions: [32, 32], bounds: [198.4, 4269350.6])
// approximate infinity: yes (psi: 2198.9948, dimension: 64, bound: 1.3115445e+10)
// 
// Challenge space
// c uniform in [-omega,omega] = [-8,8], o(c)=c, sqrt(l1(o(c)*c)) <= eta = 140
// 
// Standard deviations
// stdev1 = 6657199308.8, log(stdev1/1.55) = 32.0
// stdev2 = 12697.6, log(stdev2/1.55) = 13.0
// stdev3 = 416074956.8, log(stdev3/1.55) = 28.0
// stdev4 = 852121511526.4, log(stdev4/1.55) = 39.0
// 
// Repetition rate
// M1 = 3.3357349
// M2 = 1.4358844
// M3 = 1.0178994
// M4 = 1.0407249
// total = 5.0740155
// 
// Security
// MSIS dimension: 15
// MSIS root hermite factor: 1.0043083
// MLWE dimension: 67
// MLWE root hermite factor: 1.0043649
// 
// Proof size
// ~ 60.1855468750000 KiB
// 
// 50 bit moduli for degree 64: [1125899906840833, 1125899906839937, 1125899906837633, 1125899906826241, 1125899906824961]
// bit length of products: [49, 99, 149, 199, 249]
// inverses: [1, -162099428551732, 296975494591860, 32272507837893, -134010426262513]

#include "lazer.h"
static const limb_t _param_q_limbs[] = {509UL, 8796093022208UL};
static const int_t _param_q = {{(limb_t *)_param_q_limbs, 2, 0}};
static const limb_t _param_qminus1_limbs[] = {508UL, 8796093022208UL};
static const int_t _param_qminus1 = {{(limb_t *)_param_qminus1_limbs, 2, 0}};
static const limb_t _param_m_limbs[] = {15071697960074324853UL, 151UL};
static const int_t _param_m = {{(limb_t *)_param_m_limbs, 2, 0}};
static const limb_t _param_mby2_limbs[] = {33518442033783876469/2UL, 75UL};
static const int_t _param_mby2 = {{(limb_t *)_param_mby2_limbs, 2, 0}};
static const limb_t _param_gamma_limbs[] = {57938773644UL, 0UL};
static const int_t _param_gamma = {{(limb_t *)_param_gamma_limbs, 2, 0}};
static const limb_t _param_gammaby2_limbs[] = {28969386822UL, 0UL};
static const int_t _param_gammaby2 = {{(limb_t *)_param_gammaby2_limbs, 2, 0}};
static const limb_t _param_pow2D_limbs[] = {134217728UL, 0UL};
static const int_t _param_pow2D = {{(limb_t *)_param_pow2D_limbs, 2, 0}};
static const limb_t _param_pow2Dby2_limbs[] = {67108864UL, 0UL};
static const int_t _param_pow2Dby2 = {{(limb_t *)_param_pow2Dby2_limbs, 2, 0}};
static const limb_t _param_Bsq_limbs[] = {8915998684168819785UL, 76597UL, 0UL, 0UL};
static const int_t _param_Bsq = {{(limb_t *)_param_Bsq_limbs, 4, 0}};
static const limb_t _param_scM1_limbs[] = {16721190066534737737UL, 6193214940902648554UL, 3UL};
static const int_t _param_scM1 = {{(limb_t *)_param_scM1_limbs, 3, 0}};
static const limb_t _param_scM2_limbs[] = {10284731432140904446UL, 8040647985474542212UL, 1UL};
static const int_t _param_scM2 = {{(limb_t *)_param_scM2_limbs, 3, 0}};
static const limb_t _param_scM3_limbs[] = {9664554624427363877UL, 330185689337542107UL, 1UL};
static const int_t _param_scM3 = {{(limb_t *)_param_scM3_limbs, 3, 0}};
static const limb_t _param_scM4_limbs[] = {10738907513876077096UL, 751241270246299617UL, 1UL};
static const int_t _param_scM4 = {{(limb_t *)_param_scM4_limbs, 3, 0}};
static const limb_t _param_stdev1sq_limbs[] = {7424814489668094525UL, 2UL, 0UL, 0UL};
static const int_t _param_stdev1sq = {{(limb_t *)_param_stdev1sq_limbs, 4, 0}};
static const limb_t _param_stdev2sq_limbs[] = {161229046UL, 0UL, 0UL, 0UL};
static const int_t _param_stdev2sq = {{(limb_t *)_param_stdev2sq_limbs, 4, 0}};
static const limb_t _param_stdev3sq_limbs[] = {173118369676121866UL, 0UL, 0UL, 0UL};
static const int_t _param_stdev3sq = {{(limb_t *)_param_stdev3sq_limbs, 4, 0}};
static const limb_t _param_stdev4sq_limbs[] = {10330176681277348905UL, 39362UL, 0UL, 0UL};
static const int_t _param_stdev4sq = {{(limb_t *)_param_stdev4sq_limbs, 4, 0}};
static const limb_t _param_inv2_limbs[] = {254UL, 4398046511104UL};
static const int_t _param_inv2 = {{(limb_t *)_param_inv2_limbs, 2, 1}};
static const limb_t _param_inv4_limbs[] = {127UL, 2199023255552UL};
static const int_t _param_inv4 = {{(limb_t *)_param_inv4_limbs, 2, 1}};
static const unsigned int _param_n[2] = {32, 32};
static const limb_t _param_Bz3sqr_limbs[] = {8518042330452417392UL, 6UL, 0UL, 0UL};
static const int_t _param_Bz3sqr = {{(limb_t *)_param_Bz3sqr_limbs, 4, 0}};
static const limb_t _param_Bz4_limbs[] = {13633944184422UL, 0UL};
static const int_t _param_Bz4 = {{(limb_t *)_param_Bz4_limbs, 2, 0}};
static const limb_t _param_l2Bsq0_limbs[] = {39363UL, 0UL};
static const int_t _param_l2Bsq0 = {{(limb_t *)_param_l2Bsq0_limbs, 2, 0}};
static const limb_t _param_l2Bsq1_limbs[] = {18227354751590UL, 0UL};
static const int_t _param_l2Bsq1 = {{(limb_t *)_param_l2Bsq1_limbs, 2, 0}};
static const int_srcptr _param_l2Bsq[] = {_param_l2Bsq0, _param_l2Bsq1};
static const polyring_t _param_ring = {{_param_q, 64, 108, 6, moduli_d64, 5, _param_inv2}};
static const dcompress_params_t _param_dcomp = {{ _param_q, _param_qminus1, _param_m, _param_mby2, _param_gamma, _param_gammaby2, _param_pow2D, _param_pow2Dby2, 27, 1, 72 }};
static const abdlop_params_t _param_tbox = {{ _param_ring, _param_dcomp, 98, 93, 0, 11, 15, _param_Bsq, 1, 8, 5, 140, 1, 32, _param_scM1, _param_stdev1sq, 2, 13, _param_scM2, _param_stdev2sq}};
static const abdlop_params_t _param_quad_eval_ = {{ _param_ring, _param_dcomp, 98, 93, 9, 2, 15, _param_Bsq, 1, 8, 5, 140, 1, 32, _param_scM1, _param_stdev1sq, 2, 13, _param_scM2, _param_stdev2sq}};
static const abdlop_params_t _param_quad_many_ = {{ _param_ring, _param_dcomp, 98, 93, 10, 1, 15, _param_Bsq, 1, 8, 5, 140, 1, 32, _param_scM1, _param_stdev1sq, 2, 13, _param_scM2, _param_stdev2sq}};
static const lnp_quad_eval_params_t _param_quad_eval = {{ _param_quad_eval_, _param_quad_many_, 2}};
static const lnp_tbox_params_t _param = {{ _param_tbox, _param_quad_eval, 32, _param_n, 64, 2, 98, 2, 28, _param_scM3, _param_stdev3sq, 2, 39, _param_scM4, _param_stdev4sq, _param_Bz3sqr, _param_Bz4, &_param_l2Bsq[0], _param_inv4, 61630UL }};

static const unsigned int param_Ps[32] = {0, 1, 2, 3, 4, 5, 6, 7, 8, 9, 10, 11, 12, 13, 14, 15, 16, 17, 18, 19, 20, 21, 22, 23, 24, 25, 26, 27, 28, 29, 30, 31};
static const unsigned int param_Es0[32] = {32, 33, 34, 35, 36, 37, 38, 39, 40, 41, 42, 43, 44, 45, 46, 47, 48, 49, 50, 51, 52, 53, 54, 55, 56, 57, 58, 59, 60, 61, 62, 63};
static const unsigned int param_Es1[32] = {64, 65, 66, 67, 68, 69, 70, 71, 72, 73, 74, 75, 76, 77, 78, 79, 80, 81, 82, 83, 84, 85, 86, 87, 88, 89, 90, 91, 92, 93, 94, 95};
static const unsigned int *param_Es[2] = { param_Es0, param_Es1, };
static const unsigned int param_Es_nrows[2] = {32, 32};

static const limb_t param_p_limbs[] = {1152921504606830593UL};
static const int_t param_p = {{(limb_t *)param_p_limbs, 1, 0}};
static const limb_t param_pinv_limbs[] = {2376226138616802293UL, 1915727216006UL};
static const int_t param_pinv = {{(limb_t *)param_pinv_limbs, 2, 0}};
static const unsigned int param_s1_indices[3] = {0, 1, 2};
static const lin_params_t param = {{ _param, 2048, param_p, param_pinv, 32, param_s1_indices, 3, NULL, 0,  param_Ps, 32, param_Es, param_Es_nrows, NULL, NULL }};

