// auto-generated by lnp-quad-eval-codegen.sage from ../vdec/vdec_params.sage.
// 
// protocol is statistically complete with correctness error >= 1 - 2^(-3)
// protocol is simulatable under MLWE(43,18,[-1,1])
// protocol is knowledge-sound with knowledge error <= 2^(-127.0)
// 
// Ring
// degree d = 64
// modulus q = 295147905179352826301, log(q) ~ 68.0
// factors q = q1
// 
// Compression
// D = 11
// gamma = 895300, log(gamma) ~ 19.772012
// m = (q-1)/gamma = 329663693934271, log(m) ~ 48.227988
// 
// Dimensions of secrets
// s1: m1 = 48
// m: l = 5
// s2: m2 = 61
// 
// Size of secrets
// l2(s1) <= alpha = 1.0
// m unbounded
// s2 uniform in [-nu,nu] = [-1,1]
// 
// Challenge space
// c uniform in [-omega,omega] = [-8,8], o(c)=c, sqrt(l1(o(c)*c)) <= eta = 140
// 
// Standard deviations
// stdev1 = 1587.2, log(stdev1/1.55) = 10.0
// stdev2 = 101580.8, log(stdev2/1.55) = 16.0
// stdev4 = 3328599654.4, log(stdev4/1.55) = 31.0
// 
// Repetition rate
// M1 = 2.8508352
// M2 = 2.7806198
// M4 = 1.0
// total = 7.927089
// 
// Security
// MSIS dimension: 11
// MSIS root hermite factor: 1.0043642
// MLWE dimension: 43
// MLWE root hermite factor: 1.004348
// 
// 50 bit moduli for degree 64: [1125899906840833, 1125899906839937, 1125899906837633]
// bit length of products: [49, 99, 149]
// inverses: [1, -162099428551732, 296975494591860]

#include "lazer.h"
static const limb_t params1_q_limbs[] = {445UL, 16UL};
static const int_t params1_q = {{(limb_t *)params1_q_limbs, 2, 0}};
static const limb_t params1_qminus1_limbs[] = {444UL, 16UL};
static const int_t params1_qminus1 = {{(limb_t *)params1_qminus1_limbs, 2, 0}};
static const limb_t params1_m_limbs[] = {329663693934271UL, 0UL};
static const int_t params1_m = {{(limb_t *)params1_m_limbs, 2, 0}};
static const limb_t params1_mby2_limbs[] = {0};
static const int_t params1_mby2 = {{(limb_t *)params1_mby2_limbs, 1, 0}};
static const limb_t params1_gamma_limbs[] = {895300UL, 0UL};
static const int_t params1_gamma = {{(limb_t *)params1_gamma_limbs, 2, 0}};
static const limb_t params1_gammaby2_limbs[] = {447650UL, 0UL};
static const int_t params1_gammaby2 = {{(limb_t *)params1_gammaby2_limbs, 2, 0}};
static const limb_t params1_pow2D_limbs[] = {2048UL, 0UL};
static const int_t params1_pow2D = {{(limb_t *)params1_pow2D_limbs, 2, 0}};
static const limb_t params1_pow2Dby2_limbs[] = {1024UL, 0UL};
static const int_t params1_pow2Dby2 = {{(limb_t *)params1_pow2Dby2_limbs, 2, 0}};
static const limb_t params1_Bsq_limbs[] = {607979494581369UL, 0UL, 0UL, 0UL};
static const int_t params1_Bsq = {{(limb_t *)params1_Bsq_limbs, 4, 0}};
static const limb_t params1_scM1_limbs[] = {12930140848848264027UL, 15695139906632714302UL, 2UL};
static const int_t params1_scM1 = {{(limb_t *)params1_scM1_limbs, 3, 0}};
static const limb_t params1_scM2_limbs[] = {13190892563008942665UL, 14399893406345154812UL, 2UL};
static const int_t params1_scM2 = {{(limb_t *)params1_scM2_limbs, 3, 0}};
static const limb_t params1_scM4_limbs[] = {12262109167266519602UL, 301228718120UL, 1UL};
static const int_t params1_scM4 = {{(limb_t *)params1_scM4_limbs, 3, 0}};
static const limb_t params1_stdev1sq_limbs[] = {2519204UL, 0UL, 0UL, 0UL};
static const int_t params1_stdev1sq = {{(limb_t *)params1_stdev1sq_limbs, 4, 0}};
static const limb_t params1_stdev2sq_limbs[] = {10318658929UL, 0UL, 0UL, 0UL};
static const int_t params1_stdev2sq = {{(limb_t *)params1_stdev2sq_limbs, 4, 0}};
static const limb_t params1_stdev4sq_limbs[] = {11079575659271799439UL, 0UL, 0UL, 0UL};
static const int_t params1_stdev4sq = {{(limb_t *)params1_stdev4sq_limbs, 4, 0}};
static const limb_t params1_inv2_limbs[] = {222UL, 8UL};
static const int_t params1_inv2 = {{(limb_t *)params1_inv2_limbs, 2, 1}};
static const limb_t params1_inv4_limbs[] = {111UL, 4UL};
static const int_t params1_inv4 = {{(limb_t *)params1_inv4_limbs, 2, 1}};
static const limb_t params1_Bz4_limbs[] = {10199131011377716250UL, 413UL, 0UL, 0UL};
static const int_t params1_Bz4 = {{(limb_t *)params1_Bz4_limbs, 4, 0}};
static const polyring_t params1_ring = {{params1_q, 64, 69, 6, moduli_d64, 3, params1_inv2}};
static const dcompress_params_t params1_dcomp = {{ params1_q, params1_qminus1, params1_m, params1_mby2, params1_gamma, params1_gammaby2, params1_pow2D, params1_pow2Dby2, 11, 1, 49 }};
static const abdlop_params_t params1_quad_eval = {{ params1_ring, params1_dcomp, 48, 61, 5, 2, 11, params1_Bsq, 1, 8, 5, 140, 1, 10, params1_scM1, params1_stdev1sq, 1, 16, params1_scM2, params1_stdev2sq}};
static const abdlop_params_t params1_quad_many = {{ params1_ring, params1_dcomp, 48, 61, 6, 1, 11, params1_Bsq, 1, 8, 5, 140, 1, 10, params1_scM1, params1_stdev1sq, 1, 16, params1_scM2, params1_stdev2sq}};
static const lnp_quad_eval_params_t params1 = {{ params1_quad_eval, params1_quad_many, 2, params1_inv4, 31, params1_scM4, params1_stdev4sq, params1_Bz4}};

